// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SorryDave.JiraSync.Core.Persistence;

#nullable disable

namespace SorryDave.JiraSync.Core.Persistence.Migrations
{
    [DbContext(typeof(JiraSyncDbContext))]
    partial class JiraSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SorryDave.JiraSync.Core.Domain.ResourceMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemKey");

                    b.HasIndex("ResourceType", "ResourceId")
                        .IsUnique();

                    b.ToTable("ResourceMappings");
                });

            modelBuilder.Entity("SorryDave.JiraSync.Core.Domain.WorkItem", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JiraUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("JiraUpdated");

                    b.HasIndex("ProjectKey");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("SorryDave.JiraSync.Core.Domain.WriteBackRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JiraCommentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.HasIndex("WorkItemKey", "RecordIdentity")
                        .IsUnique();

                    b.ToTable("WriteBackRecords");
                });

            modelBuilder.Entity("SorryDave.JiraSync.Core.Domain.ResourceMapping", b =>
                {
                    b.HasOne("SorryDave.JiraSync.Core.Domain.WorkItem", "WorkItem")
                        .WithMany("Mappings")
                        .HasForeignKey("WorkItemKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("SorryDave.JiraSync.Core.Domain.WorkItem", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
